export const CATEGORIES = [
  { id: 'all', label: 'All' },
  { id: 'books', label: 'Books' },
  { id: 'electronics', label: 'Electronics' },
  { id: 'daily-essentials', label: 'Daily essentials' },
  { id: 'others', label: 'Others' },
];

export const INITIAL_LISTINGS = [
  {
    id: 1,
    title: 'K.D. Tripathi Pharmacology 8th Ed',
    price: 1400,
    condition: 'Like New',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?auto=format&fit=crop&q=80&w=600&h=600',
    seller: { name: 'Rahul S.', phone: '919876543210' },
    location: 'Central Library',
    description: 'Barely used, no highlights. Includes original index. Need to sell before semester ends.',
    postedAgo: '2 hours ago',
  },
  {
    id: 2,
    title: 'Littmann Classic III Stethoscope',
    price: 8500,
    condition: 'Good',
    category: 'others',
    image: 'https://images.unsplash.com/photo-1584982751601-97dcc096659c?auto=format&fit=crop&q=80&w=600&h=600',
    seller: { name: 'Priya K.', phone: '919876543211' },
    location: 'Block B Cafeteria',
    description: 'Black edition, fully functional. Upgrading to cardiology model.',
    postedAgo: '5 hours ago',
  },
  {
    id: 3,
    title: 'Lab Coat / Apron (Size M)',
    price: 400,
    condition: 'Fair',
    category: 'daily-essentials',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&q=80&w=600&h=600',
    seller: { name: 'Ankit M.', phone: '919876543212' },
    location: 'Academic Block A Gate',
    description: 'Washed and ironed. Small ink stain near bottom hem.',
    postedAgo: '1 day ago',
  },
  {
    id: 4,
    title: 'LED Study Lamp',
    price: 350,
    condition: 'Like New',
    category: 'daily-essentials',
    image: 'https://images.unsplash.com/photo-1513506003901-1e6a229e2d15?auto=format&fit=crop&q=80&w=600&h=600',
    seller: { name: 'Sneha R.', phone: '919876543213' },
    location: 'Common Room Lobby',
    description: 'LED desk lamp, 3 brightness modes, USB rechargeable. 3 months old.',
    postedAgo: '2 days ago',
  },
  {
    id: 5,
    title: "Gray's Anatomy 41st Edition",
    price: 2200,
    condition: 'Good',
    category: 'books',
    image: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?auto=format&fit=crop&q=80&w=600&h=600',
    seller: { name: 'Vikram N.', phone: '919876543214' },
    location: 'Library Reading Room',
    description: 'Some notes in pencil in margins. Spine intact. Great for final year.',
    postedAgo: '3 days ago',
  },
  {
    id: 6,
    title: 'Portable Bluetooth Speaker',
    price: 900,
    condition: 'Good',
    category: 'electronics',
    image: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?auto=format&fit=crop&q=80&w=600&h=600',
    seller: { name: 'Megha P.', phone: '919876543215' },
    location: 'Campus Canteen',
    description: 'JBL Go 2. Works perfectly, comes with charging cable.',
    postedAgo: '4 days ago',
  },
];
